export const lawyersData = [
  {
    name: "Anil Bhatia",
    state: "Haryana",
    city: "Faridabad",
    practice_areas: ["Corporate Law", "Tax Law"],
    contact: {
      email: "anil.bhatia@example.com",
      phone: "+91 98765 43230",
    },
    experience_years: 10,
  },
  {
    name: "Deepika Srinivasan",
    state: "Tamil Nadu",
    city: "Madurai",
    practice_areas: ["Family Law", "Civil Law"],
    contact: {
      email: "deepika.srinivasan@example.com",
      phone: "+91 98765 43231",
    },
    experience_years: 9,
  },
  {
    name: "Rajat Mehra",
    state: "Uttar Pradesh",
    city: "Agra",
    practice_areas: ["Criminal Law", "Labour Law"],
    contact: {
      email: "rajat.mehra@example.com",
      phone: "+91 98765 43232",
    },
    experience_years: 13,
  },
  {
    name: "Swati Kapoor",
    state: "Rajasthan",
    city: "Jodhpur",
    practice_areas: ["Real Estate", "Property Disputes"],
    contact: {
      email: "swati.kapoor@example.com",
      phone: "+91 98765 43233",
    },
    experience_years: 11,
  },
  {
    name: "Kunal Desai",
    state: "Gujarat",
    city: "Vadodara",
    practice_areas: ["Intellectual Property", "Corporate Law"],
    contact: {
      email: "kunal.desai@example.com",
      phone: "+91 98765 43234",
    },
    experience_years: 7,
  },
  {
    name: "Nandini Reddy",
    state: "Telangana",
    city: "Warangal",
    practice_areas: ["Civil Law", "Family Law"],
    contact: {
      email: "nandini.reddy@example.com",
      phone: "+91 98765 43235",
    },
    experience_years: 12,
  },
  {
    name: "Vishal Gupta",
    state: "Punjab",
    city: "Amritsar",
    practice_areas: ["Criminal Law", "Labour Law"],
    contact: {
      email: "vishal.gupta@example.com",
      phone: "+91 98765 43236",
    },
    experience_years: 15,
  },
  {
    name: "Anita Menon",
    state: "Kerala",
    city: "Kozhikode",
    practice_areas: ["Environmental Law", "Civil Law"],
    contact: {
      email: "anita.menon@example.com",
      phone: "+91 98765 43237",
    },
    experience_years: 8,
  },
  {
    name: "Rakesh Sharma",
    state: "Himachal Pradesh",
    city: "Shimla",
    practice_areas: ["Family Law", "Property Disputes"],
    contact: {
      email: "rakesh.sharma@example.com",
      phone: "+91 98765 43238",
    },
    experience_years: 14,
  },
  {
    name: "Shalini Nair",
    state: "Kerala",
    city: "Thrissur",
    practice_areas: ["Corporate Law", "Tax Law"],
    contact: {
      email: "shalini.nair@example.com",
      phone: "+91 98765 43239",
    },
    experience_years: 10,
  },
  {
    name: "Aryan Kapoor",
    state: "Maharashtra",
    city: "Nagpur",
    practice_areas: ["Criminal Law", "Labour Law"],
    contact: {
      email: "aryan.kapoor@example.com",
      phone: "+91 98765 43240",
    },
    experience_years: 11,
  },
  {
    name: "Divya Iyer",
    state: "Tamil Nadu",
    city: "Tiruchirappalli",
    practice_areas: ["Civil Law", "Real Estate"],
    contact: {
      email: "divya.iyer@example.com",
      phone: "+91 98765 43241",
    },
    experience_years: 9,
  },
  {
    name: "Rohit Joshi",
    state: "Uttarakhand",
    city: "Dehradun",
    practice_areas: ["Constitutional Law", "Labour Law"],
    contact: {
      email: "rohit.joshi@example.com",
      phone: "+91 98765 43242",
    },
    experience_years: 12,
  },
  {
    name: "Meghna Patel",
    state: "Gujarat",
    city: "Rajkot",
    practice_areas: ["Intellectual Property", "Corporate Law"],
    contact: {
      email: "meghna.patel@example.com",
      phone: "+91 98765 43243",
    },
    experience_years: 7,
  },
  {
    name: "Arvind Singh",
    state: "Bihar",
    city: "Patna",
    practice_areas: ["Criminal Law", "Family Law"],
    contact: {
      email: "arvind.singh@example.com",
      phone: "+91 98765 43244",
    },
    experience_years: 16,
  },
  {
    name: "Kavita Reddy",
    state: "Andhra Pradesh",
    city: "Vijayawada",
    practice_areas: ["Civil Law", "Property Disputes"],
    contact: {
      email: "kavita.reddy@example.com",
      phone: "+91 98765 43245",
    },
    experience_years: 10,
  },
  {
    name: "Pranav Kumar",
    state: "Jharkhand",
    city: "Ranchi",
    practice_areas: ["Labour Law", "Corporate Law"],
    contact: {
      email: "pranav.kumar@example.com",
      phone: "+91 98765 43246",
    },
    experience_years: 13,
  },
  {
    name: "Sonia Mehra",
    state: "Uttar Pradesh",
    city: "Varanasi",
    practice_areas: ["Family Law", "Civil Law"],
    contact: {
      email: "sonia.mehra@example.com",
      phone: "+91 98765 43247",
    },
    experience_years: 11,
  },
  {
    name: "Rajiv Nair",
    state: "Kerala",
    city: "Kollam",
    practice_areas: ["Environmental Law", "Civil Law"],
    contact: {
      email: "rajiv.nair@example.com",
      phone: "+91 98765 43248",
    },
    experience_years: 9,
  },
  {
    name: "Anjali Deshmukh",
    state: "Maharashtra",
    city: "Nashik",
    practice_areas: ["Criminal Law", "Labour Law"],
    contact: {
      email: "anjali.deshmukh@example.com",
      phone: "+91 98765 43249",
    },
    experience_years: 14,
  },

  {
    name: "Aarav Sharma",
    state: "Maharashtra",
    city: "Mumbai",
    practice_areas: ["Criminal Law", "Family Law"],
    contact: {
      email: "aarav.sharma@example.com",
      phone: "+91 98765 43210",
    },
    experience_years: 12,
  },
  {
    name: "Priya Patel",
    state: "Gujarat",
    city: "Ahmedabad",
    practice_areas: ["Corporate Law", "Intellectual Property"],
    contact: {
      email: "priya.patel@example.com",
      phone: "+91 98765 43211",
    },
    experience_years: 8,
  },
  {
    name: "Rahul Singh",
    state: "Delhi",
    city: "New Delhi",
    practice_areas: ["Civil Law", "Real Estate"],
    contact: {
      email: "rahul.singh@example.com",
      phone: "+91 98765 43212",
    },
    experience_years: 15,
  },
  {
    name: "Ananya Reddy",
    state: "Telangana",
    city: "Hyderabad",
    practice_areas: ["Tax Law", "Corporate Law"],
    contact: {
      email: "ananya.reddy@example.com",
      phone: "+91 98765 43213",
    },
    experience_years: 10,
  },
  {
    name: "Vikram Joshi",
    state: "Uttar Pradesh",
    city: "Lucknow",
    practice_areas: ["Labour Law", "Constitutional Law"],
    contact: {
      email: "vikram.joshi@example.com",
      phone: "+91 98765 43214",
    },
    experience_years: 18,
  },
  {
    name: "Meera Desai",
    state: "Karnataka",
    city: "Bengaluru",
    practice_areas: ["Cyber Law", "Intellectual Property"],
    contact: {
      email: "meera.desai@example.com",
      phone: "+91 98765 43215",
    },
    experience_years: 7,
  },
  {
    name: "Arjun Kapoor",
    state: "Rajasthan",
    city: "Jaipur",
    practice_areas: ["Family Law", "Property Disputes"],
    contact: {
      email: "arjun.kapoor@example.com",
      phone: "+91 98765 43216",
    },
    experience_years: 11,
  },
  {
    name: "Kavita Iyer",
    state: "Tamil Nadu",
    city: "Chennai",
    practice_areas: ["Banking Law", "Corporate Law"],
    contact: {
      email: "kavita.iyer@example.com",
      phone: "+91 98765 43217",
    },
    experience_years: 14,
  },
  {
    name: "Rajesh Menon",
    state: "Kerala",
    city: "Kochi",
    practice_areas: ["Environmental Law", "Civil Law"],
    contact: {
      email: "rajesh.menon@example.com",
      phone: "+91 98765 43218",
    },
    experience_years: 9,
  },
  {
    name: "Sneha Gupta",
    state: "Punjab",
    city: "Chandigarh",
    practice_areas: ["Criminal Law", "Labour Law"],
    contact: {
      email: "sneha.gupta@example.com",
      phone: "+91 98765 43219",
    },
    experience_years: 13,
  },
  {
    name: "Rohan Malhotra",
    state: "Haryana",
    city: "Gurgaon",
    practice_areas: ["Corporate Law", "Tax Law"],
    contact: {
      email: "rohan.malhotra@example.com",
      phone: "+91 98765 43220",
    },
    experience_years: 6,
  },
  {
    name: "Anjali Rao",
    state: "Andhra Pradesh",
    city: "Visakhapatnam",
    practice_areas: ["Family Law", "Civil Law"],
    contact: {
      email: "anjali.rao@example.com",
      phone: "+91 98765 43221",
    },
    experience_years: 10,
  },
  {
    name: "Vivek Nair",
    state: "Kerala",
    city: "Thiruvananthapuram",
    practice_areas: ["Constitutional Law", "Labour Law"],
    contact: {
      email: "vivek.nair@example.com",
      phone: "+91 98765 43222",
    },
    experience_years: 16,
  },
  {
    name: "Pooja Mehta",
    state: "Gujarat",
    city: "Surat",
    practice_areas: ["Intellectual Property", "Corporate Law"],
    contact: {
      email: "pooja.mehta@example.com",
      phone: "+91 98765 43223",
    },
    experience_years: 9,
  },
  {
    name: "Suresh Kumar",
    state: "Tamil Nadu",
    city: "Coimbatore",
    practice_areas: ["Real Estate", "Civil Law"],
    contact: {
      email: "suresh.kumar@example.com",
      phone: "+91 98765 43224",
    },
    experience_years: 12,
  },
  {
    name: "Neha Choudhary",
    state: "Rajasthan",
    city: "Udaipur",
    practice_areas: ["Family Law", "Property Disputes"],
    contact: {
      email: "neha.choudhary@example.com",
      phone: "+91 98765 43225",
    },
    experience_years: 7,
  },
  {
    name: "Amit Trivedi",
    state: "Madhya Pradesh",
    city: "Indore",
    practice_areas: ["Criminal Law", "Labour Law"],
    contact: {
      email: "amit.trivedi@example.com",
      phone: "+91 98765 43226",
    },
    experience_years: 14,
  },
  {
    name: "Shreya Banerjee",
    state: "West Bengal",
    city: "Kolkata",
    practice_areas: ["Corporate Law", "Tax Law"],
    contact: {
      email: "shreya.banerjee@example.com",
      phone: "+91 98765 43227",
    },
    experience_years: 11,
  },
  {
    name: "Ravi Verma",
    state: "Uttar Pradesh",
    city: "Kanpur",
    practice_areas: ["Civil Law", "Real Estate"],
    contact: {
      email: "ravi.verma@example.com",
      phone: "+91 98765 43228",
    },
    experience_years: 17,
  },
  {
    name: "Kiran Deshmukh",
    state: "Maharashtra",
    city: "Pune",
    practice_areas: ["Intellectual Property", "Cyber Law"],
    contact: {
      email: "kiran.deshmukh@example.com",
      phone: "+91 98765 43229",
    },
    experience_years: 8,
  },

  {
    name: "Aarohi Khanna",
    state: "Punjab",
    city: "Ludhiana",
    practice_areas: ["Criminal Law", "Family Law"],
    contact: {
      email: "aarohi.khanna@example.com",
      phone: "+91 98765 43250",
    },
    experience_years: 11,
  },
  {
    name: "Rishabh Malhotra",
    state: "Haryana",
    city: "Panipat",
    practice_areas: ["Corporate Law", "Tax Law"],
    contact: {
      email: "rishabh.malhotra@example.com",
      phone: "+91 98765 43251",
    },
    experience_years: 9,
  },
  {
    name: "Ishani Chatterjee",
    state: "West Bengal",
    city: "Howrah",
    practice_areas: ["Civil Law", "Real Estate"],
    contact: {
      email: "ishani.chatterjee@example.com",
      phone: "+91 98765 43252",
    },
    experience_years: 12,
  },
  {
    name: "Karan Oberoi",
    state: "Himachal Pradesh",
    city: "Dharamshala",
    practice_areas: ["Labour Law", "Constitutional Law"],
    contact: {
      email: "karan.oberoi@example.com",
      phone: "+91 98765 43253",
    },
    experience_years: 8,
  },
  {
    name: "Mira Sen",
    state: "Assam",
    city: "Guwahati",
    practice_areas: ["Family Law", "Property Disputes"],
    contact: {
      email: "mira.sen@example.com",
      phone: "+91 98765 43254",
    },
    experience_years: 10,
  },
  {
    name: "Vedant Kapoor",
    state: "Uttarakhand",
    city: "Haridwar",
    practice_areas: ["Environmental Law", "Civil Law"],
    contact: {
      email: "vedant.kapoor@example.com",
      phone: "+91 98765 43255",
    },
    experience_years: 7,
  },
  {
    name: "Anaya Bhat",
    state: "Jammu and Kashmir",
    city: "Srinagar",
    practice_areas: ["Criminal Law", "Labour Law"],
    contact: {
      email: "anaya.bhat@example.com",
      phone: "+91 98765 43256",
    },
    experience_years: 13,
  },
  {
    name: "Rohan Dutta",
    state: "Odisha",
    city: "Bhubaneswar",
    practice_areas: ["Corporate Law", "Intellectual Property"],
    contact: {
      email: "rohan.dutta@example.com",
      phone: "+91 98765 43257",
    },
    experience_years: 11,
  },
  {
    name: "Sanya Mehra",
    state: "Chhattisgarh",
    city: "Raipur",
    practice_areas: ["Civil Law", "Family Law"],
    contact: {
      email: "sanya.mehra@example.com",
      phone: "+91 98765 43258",
    },
    experience_years: 9,
  },
  {
    name: "Arnav Singh",
    state: "Bihar",
    city: "Gaya",
    practice_areas: ["Criminal Law", "Labour Law"],
    contact: {
      email: "arnav.singh@example.com",
      phone: "+91 98765 43259",
    },
    experience_years: 14,
  },
  {
    name: "Tanya Reddy",
    state: "Telangana",
    city: "Nizamabad",
    practice_areas: ["Tax Law", "Corporate Law"],
    contact: {
      email: "tanya.reddy@example.com",
      phone: "+91 98765 43260",
    },
    experience_years: 10,
  },
  {
    name: "Rajat Verma",
    state: "Uttar Pradesh",
    city: "Allahabad",
    practice_areas: ["Civil Law", "Real Estate"],
    contact: {
      email: "rajat.verma@example.com",
      phone: "+91 98765 43261",
    },
    experience_years: 12,
  },
  {
    name: "Kavya Nair",
    state: "Kerala",
    city: "Kannur",
    practice_areas: ["Family Law", "Property Disputes"],
    contact: {
      email: "kavya.nair@example.com",
      phone: "+91 98765 43262",
    },
    experience_years: 8,
  },
  {
    name: "Aryan Desai",
    state: "Gujarat",
    city: "Bhavnagar",
    practice_areas: ["Intellectual Property", "Corporate Law"],
    contact: {
      email: "aryan.desai@example.com",
      phone: "+91 98765 43263",
    },
    experience_years: 11,
  },
  {
    name: "Neha Kapoor",
    state: "Rajasthan",
    city: "Ajmer",
    practice_areas: ["Criminal Law", "Labour Law"],
    contact: {
      email: "neha.kapoor@example.com",
      phone: "+91 98765 43264",
    },
    experience_years: 15,
  },
  {
    name: "Vihaan Iyer",
    state: "Tamil Nadu",
    city: "Salem",
    practice_areas: ["Civil Law", "Family Law"],
    contact: {
      email: "vihaan.iyer@example.com",
      phone: "+91 98765 43265",
    },
    experience_years: 9,
  },
  {
    name: "Anika Rao",
    state: "Karnataka",
    city: "Mysore",
    practice_areas: ["Corporate Law", "Tax Law"],
    contact: {
      email: "anika.rao@example.com",
      phone: "+91 98765 43266",
    },
    experience_years: 10,
  },
  {
    name: "Rudra Patel",
    state: "Madhya Pradesh",
    city: "Bhopal",
    practice_areas: ["Labour Law", "Constitutional Law"],
    contact: {
      email: "rudra.patel@example.com",
      phone: "+91 98765 43267",
    },
    experience_years: 12,
  },
  {
    name: "Zoya Khan",
    state: "Uttar Pradesh",
    city: "Meerut",
    practice_areas: ["Criminal Law", "Family Law"],
    contact: {
      email: "zoya.khan@example.com",
      phone: "+91 98765 43268",
    },
    experience_years: 11,
  },
  {
    name: "Aarav Menon",
    state: "Kerala",
    city: "Thiruvananthapuram",
    practice_areas: ["Environmental Law", "Civil Law"],
    contact: {
      email: "aarav.menon@example.com",
      phone: "+91 98765 43269",
    },
    experience_years: 10,
  },
];
